#spring:
#  redis:
#    host: local-redis
#    port: 6379 # connection port
#    password: 123456
#    database: 0

spring:
  redis:
    database: 0
    host: local-redis
    port: 6379
    password: 123456
    max-idle: 8
    min-idle: 1
    max-active: 8
    max-wait: -1
